# Generated by Django 4.2.7 on 2026-01-03 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0005_studentanswer_examsession_current_question_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.PositiveIntegerField(help_text='Reference to the exam session')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('answers_data', models.JSONField(default=dict, help_text='Snapshot of answers with scores')),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('grading_method', models.CharField(default='auto', help_text='auto, manual, expired', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to='assessments.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade History',
                'verbose_name_plural': 'Grade Histories',
                'db_table': 'grade_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'exam'], name='grade_histo_student_1459b2_idx'), models.Index(fields=['status'], name='grade_histo_status_882356_idx'), models.Index(fields=['-created_at'], name='grade_histo_created_440626_idx')],
            },
        ),
    ]
