# Generated by Django 4.2.7 on 2026-01-03 10:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the exam in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('course', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GRADED', 'Graded'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('SHORT_ANSWER', 'Short Answer'), ('ESSAY', 'Essay'), ('MULTIPLE_CHOICE', 'Multiple Choice')], default='SHORT_ANSWER', max_length=20)),
                ('expected_answer', models.TextField(help_text='Expected answer or answer key for grading')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of the question within the exam')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.exam')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course'], name='exams_course_638104_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_active'], name='exams_is_acti_5cee66_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['-created_at'], name='exams_created_2092f0_idx'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.submission'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'exam'], name='submissions_student_98b79b_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['exam', 'status'], name='submissions_exam_id_770894_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-submitted_at'], name='submissions_submitt_113cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_dcc854_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order'], name='questions_exam_id_6a4fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='questions_questio_8af709_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'order')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['submission', 'question'], name='answers_submiss_4fd023_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['submission'], name='answers_submiss_1e8504_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('submission', 'question')},
        ),
    ]
