# Generated by Django 4.2.7 on 2026-01-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_answer_options_alter_exam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of options for multiple choice questions (e.g., ["A", "B", "C", "D"])'),
        ),
    ]
