# Generated by Django 4.2.7 on 2026-01-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='Allow multiple answers to be selected (only for MULTIPLE_CHOICE questions)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='expected_answer',
            field=models.TextField(help_text='Expected answer or answer key for grading. For multiple choice with allow_multiple=True, use JSON array like ["A", "B"]'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of option objects for multiple choice questions. Format: [{"label": "A", "value": "Paris"}, {"label": "B", "value": "London"}]'),
        ),
    ]
