# Generated by Django 4.2.7 on 2026-01-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_question_allow_multiple_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'db_table': 'student_answers',
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='current_question_order',
            field=models.PositiveIntegerField(default=1, help_text='Current question being viewed'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='socket_channel',
            field=models.CharField(blank=True, help_text='WebSocket channel for this session', max_length=100),
        ),
        migrations.AddField(
            model_name='examsession',
            name='submission_type',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AUTO_EXPIRED', 'Auto Expired')], max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['is_completed', 'expires_at'], name='exam_sessio_is_comp_4b55dc_idx'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='assessments.examsession'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['session', 'question'], name='student_ans_session_d92dff_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['session'], name='student_ans_session_a67a2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('session', 'question')},
        ),
    ]
