# Generated by Django 4.2.7 on 2026-01-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_studentanswer_examsession_current_question_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='socket_channel',
        ),
    ]
