# Generated by Django 4.2.7 on 2026-01-03 15:28

import secrets
from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    """Generate unique tokens for existing ExamSession records."""
    ExamSession = apps.get_model('assessments', 'ExamSession')
    for session in ExamSession.objects.all():
        session.token = secrets.token_urlsafe(32)
        session.save(update_fields=['token'])


def reverse_tokens(apps, schema_editor):
    """Reverse migration - set tokens to empty."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_remove_examsession_socket_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='is_token_valid',
            field=models.BooleanField(default=True, help_text='False when token is blacklisted'),
        ),
        # First add token without unique constraint
        migrations.AddField(
            model_name='examsession',
            name='token',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        # Generate unique tokens for existing rows
        migrations.RunPython(generate_unique_tokens, reverse_tokens),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='examsession',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['token'], name='exam_sessio_token_29409f_idx'),
        ),
    ]
