# Generated by Django 4.2.7 on 2026-01-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_examsession_is_token_valid_examsession_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Session Token',
                'verbose_name_plural': 'Session Tokens',
                'db_table': 'session_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='examsession',
            name='exam_sessio_token_29409f_idx',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='is_token_valid',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='token',
        ),
        migrations.AddField(
            model_name='sessiontoken',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='assessments.examsession'),
        ),
        migrations.AddIndex(
            model_name='sessiontoken',
            index=models.Index(fields=['token'], name='session_tok_token_70f8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontoken',
            index=models.Index(fields=['session', 'is_valid'], name='session_tok_session_aa53a9_idx'),
        ),
    ]
